name: App Hub Publish

env:
  D2_APP_HUB_API_KEY: ${{secrets.D2_APP_HUB_API_KEY}}

# Controls when the action will run.
on:
  # Triggers the workflow when a new release is created
  release:
    types: [ released ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install JS dependencies
        run: pnpm  install --frozen-lockfile

      - name: Build
        run: pnpm build
      # Publish to the App Hub
      - name: Set channel
        id: set_channel
        run: |
          release_name="${{ github.event.release.name }}"
          channel="stable"
          if [[ "$release_name" == *"alpha"* ]]; then
            channel="alpha"
          elif [[ "$release_name" == *"beta"* ]]; then
            channel="beta"
          fi
          echo "channel=$channel" >> $GITHUB_OUTPUT
      - name: Release to DHIS2 App Hub
        run: pnpm publish:apphub --channel ${{ steps.set_channel.outputs.channel }}
